### ISSUE TITLE
Test Case Implementation

### ISSUE THREAD

**Issue by GoldenCoqui** [GoldenCoqui/cs325-project4#1]
Need test cases for 

- Testing API responses
- Testing file paths
- Check environment requirements
- Test for heading and summary

**Comment by swarnimup** [comment]
I’ve developed a series of test cases to ensure our project's functionality is performing as expected. You’ll find these in the tests folder:

test_api_key.py: Validates that the API key is being correctly read and handled.
test_api_model.py: Checks whether the AI model is correctly loaded and operational.
test_api_response.py: Ensures that our API is returning the expected responses.
test_urls.py: Verifies that the URL processing is accurate and functional.
test_word_count.py: Tests the word count feature to confirm it’s counting words properly.
To run these tests, navigate to the main directory that contains the src folder – the same level that has the Data directory. This is where you should run pytest from the terminal. Make sure pytest is installed; if not, you can add it to your environment via pip.

Once you've got pytest set up, launch the tests by typing pytest into the terminal. This will automatically run through all the test scripts and provide you with a status report detailing which tests passed and which, if any, didn’t. In case a test fails, pytest will provide detailed output to help you pinpoint the issue.

The branch with all these updates is swarnim, ready for you to pull and execute the tests.

**Comment by swarnimup** [comment]
I've tailored a set of test cases for the cs325-project4 to ensure that key aspects of the system are functioning correctly. You can find these tests within the tests directory:

test_api_response.py: Confirms the API's ability to generate a summary given an article input.
test_file_paths.py: Verifies the correct configuration and accessibility of file paths used within the project.
test_environment.py: Checks for proper environment setup, including the presence and validity of necessary environmental variables.
test_summary.py: Assesses whether the summarization includes headings correctly and generates a non-empty summary.
To run these tests, position yourself in the root directory, at the same level as src and Data. Ensure that you have pytest installed in your Python environment; if not, it can be installed via pip with pip install pytest.

With pytest ready, initiate the tests by entering pytest in your terminal command line. pytest will run the suite and report the outcomes, telling you which tests have passed and which ones have failed, along with an explanation for any failures.

All the latest test scripts are present in the swarnim branch, where you can fetch them to conduct your testing.

**Comment by GoldenCoqui** [comment]
Looks Good
