### ISSUE TITLE
Test_Case_Implementation

### ISSUE THREAD

**Issue by swarnimup** [GoldenCoqui/cs325-project4#2]
Need test cases for
> Testing the article length
> Testing the URL's
> Testing the API model
> Testing for an API key in docs

**Comment by GoldenCoqui** [comment]
Hey I was able to make test cases for the stuff you wanted to test for.  The files are named...

- test_api_key.py (src/tests/test_api_key.py)
- test_urls.py (src/tests/test_urls.py)
- test_word_count.py (src/tests/test_word_count.py)
- test_api_model.py (src/test_api_model.py)

All of the programs will run with pytest, you have to be outside the src file to run the pytest successfully (in the terminal).  **Make sure you have pytest downloaded in your enviroment.**  Once you get the package downloaded you can run pytest by typing pytest and hitting enter (in the terminal).  Pytest will run the test cases and return a test result with either passes or fails and if there is a fail the pytest will tell you why. 

The first three programs in the list above do not have any code in other parts of the program (they are self contained in the program file they are in).  However test_api_model.py uses a get_model() in ai_summary.py (src/ai_summary.py).  The get_model() is on line 42 of ai_summary.py and was created specifically for the test_api_model test case. 

The code will be in my branch (leo-branch)

**Comment by swarnimup** [comment]
Went through your code and It’s working.

**Comment by swarnimup** [comment]
I went through the code and It is working

**Comment by swarnimup** [comment]
Its working
